runtime: python37
default_expiration: "14d"
# the export takes way way over 10 minutes, which is the task limit for auto scaling, so have to
# use basic scaling
basic_scaling:
  max_instances: 15


handlers:
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: auto
  secure: always

